export const DELIVER_DRAWER_PIXEL_EVENT_ID = 'shipping-option-deliver-to'
export const STORE_DRAWER_PIXEL_EVENT_ID = 'shipping-option-store'
export const SHIPPING_INFO_COOKIE = 'shipping_info'
export const PRODUCTS_NOT_FOUND_ERROR_CODE = 'products-not-found-error'
export const SHIPPING_MODAL_PIXEL_EVENT_ID = 'item-added-to-cart-shipping-modal'
